### ISSUE TITLE
Проблема при запуске бота 

### ISSUE THREAD

**Issue by laminda** [SegYT/ochko_boga#1]
Здравствуйте! столкнулся со следующей проблемой: 
"Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from telebot import types
  File "C:\Users\Сергей\PycharmProjects\pythonProject7\pythonProject\lib\site-packages\telebot\types.py", line 12, in <module>
    from telebot import util
  File "C:\Users\Сергей\PycharmProjects\pythonProject7\pythonProject\lib\site-packages\telebot\util.py", line 322, in <module>
    def user_link(user: types.User, include_id: bool=False) -> str:
AttributeError: partially initialized module 'telebot.types' has no attribute 'User' (most likely due to a circular import)
"

**Comment by dimondevceo** [comment]
Здравствуйте,
Это проблема в pyTelegramBotAPI dependencies.
Это решается очень просто, нужно прописать команды:

`pip uninstall pyTelegramBotAPI`

`pip uninstall telebot`

`pip install pyTelegramBotAPI`
